[tool.poetry]
name = "nanomd"
version = "0.1.0"
description = ""
authors = ["DeYing Zhang <legendzdy@dingtalk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.15.1"
pysam = "^0.22.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
